# Generated by Django 5.0.6 on 2024-12-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPELEARNING', '0002_utilisateur_groups_utilisateur_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='niveau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
