# Generated by Django 5.0.6 on 2025-01-03 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APPELEARNING", "0007_matiere1bac_cours_delete_cours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matiere1bac",
            name="cours",
        ),
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("contenu", models.TextField(blank=True, null=True)),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours",
                        to="APPELEARNING.matiere1bac",
                    ),
                ),
            ],
        ),
    ]
