# Generated by Django 5.0.6 on 2025-01-03 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APPELEARNING", "0009_cours1bac_delete_cours"),
    ]

    operations = [
        migrations.CreateModel(
            name="videos1bac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Titre", models.CharField(max_length=255)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="APPELEARNING.cours1bac",
                    ),
                ),
            ],
        ),
    ]
