# Generated by Django 5.0.6 on 2025-01-03 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APPELEARNING", "0010_videos1bac"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videos1bac",
            name="video",
        ),
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("contenu", models.TextField(blank=True, null=True)),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours",
                        to="APPELEARNING.matiere1bac",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("fichier", models.FileField(upload_to="videos/")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="APPELEARNING.cours",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Cours1bac",
        ),
        migrations.DeleteModel(
            name="videos1bac",
        ),
    ]
