# Generated by Django 5.0.6 on 2025-01-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "APPELEARNING",
            "0011_remove_videos1bac_video_cours_video_delete_cours1bac_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="fichiers_videos",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
