# Generated by Django 5.0.6 on 2025-01-03 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("APPELEARNING", "0012_cours_fichiers_videos_delete_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cours",
            name="fichiers_videos",
        ),
    ]
