# Generated by Django 5.0.6 on 2025-01-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APPELEARNING", "0013_remove_cours_fichiers_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="fichiers_videos",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
