# Generated by Django 5.0.6 on 2025-01-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APPELEARNING", "0014_cours_fichiers_videos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cours",
            name="fichiers_videos",
        ),
        migrations.AddField(
            model_name="cours",
            name="videos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
