# Generated by Django 5.0.6 on 2025-01-03 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("APPELEARNING", "0016_remove_cours_videos_cours_fichiers_videos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cours",
            name="contenu",
        ),
    ]
