# Generated by Django 5.0.6 on 2025-01-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APPELEARNING", "0017_remove_cours_contenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="contenu",
            field=models.TextField(blank=True, null=True),
        ),
    ]
