# Generated by Django 5.0.6 on 2025-01-07 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APPELEARNING", "0020_cours1bac_delete_cours"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere1bac",
            name="niveau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matieres",
                to="APPELEARNING.niveau",
            ),
        ),
    ]
