# Generated by Django 5.0.6 on 2025-01-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APPELEARNING", "0021_matiere1bac_niveau"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("contenu", models.TextField()),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapitres",
                        to="APPELEARNING.cours1bac",
                    ),
                ),
            ],
        ),
    ]
